server:
  port: 80
  time-zone: Asia/Seoul

spring:
  application:
    name: SteamProject

  # datasource 설정
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${HOSTNAME}:${PORT}/${DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    username: ${USERNAME}
#    password: ${PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws-news-rds.c1s0mwa6am7e.ap-northeast-2.rds.amazonaws.com:3306/aws_news_rds?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: admin1234

  # security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLEID}
            client-secret: ${GOOGLEPASSWORD}
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#cors 관련 설정값들
jwt:
  secret: ${JWTSECRET}
cors:
  allowed-origins: ${CORS}

app:
  oauth2:
    password: ${OAUTH2PASSWORD}
