server:
  port: 80
  time-zone: Asia/Seoul

spring:
  application:
    name: SteamProject

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}


  # security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLEID}
            client-secret: ${GOOGLEPASSWORD}
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#cors 관련 설정값들
jwt:
  secret: ${JWTSECRET}
cors:
  allowed-origins: ${CORS}

app:
  oauth2:
    password: ${OAUTH2PASSWORD}
